version: 0.2
run-as: root
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Logging in to Docker hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
    
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 9087172655/$IMAGE_REPO_NAME:$IMAGE_TAG
      
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed okay on `date`
      - echo Pushing the Docker yes to yes image...
      - docker push 9087172655/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo Proceed to docker run. Published image in ecr

      